### ISSUE TITLE
Objects are rendered with the wrong aspect ratio

### ISSUE THREAD

**Issue by jc86035** [xingrz/rdt-editor#1]
I tested this editor using the diagram code of [w:en:Template:East London Line RDT](https://en.wikipedia.org/wiki/Template:East_London_Line_RDT).

The main issue that would prevent me from using this editor is that every object is rendered as 20px × 20px regardless of the aspect ratio. For files it looks like the width and height can be obtained using [an API request](https://en.wikipedia.org/w/api.php?action=query&format=json&prop=imageinfo&iiprop=size&titles=File:BSicon_STR.svg) (multiply the width by <sup>20</sup>⁄<sub>height</sub> to get the display width), and for text and filler cells you can use [the definitions in the {{Routemap}} CSS](https://commons.wikimedia.org/wiki/Template:Routemap/styles.css).

**Comment by xingrz** [comment]
![image](https://user-images.githubusercontent.com/288288/74115708-67420880-4beb-11ea-8d3b-a77cbb4e38d7.png)

Fixed. Thank you.
