### ISSUE TITLE
Text cells that are not square are not recognized as text cells

### ISSUE THREAD

**Issue by jc86035** [xingrz/rdt-editor#2]
The format for Routemap text cells is `width*text`, where `width` can be matched by the regex `\+?(o?c?d?|c?d?b?|d?b?s?|b?s?w?)` (these are the values that the Routemap CSS currently supports) and `text` may be any text which does not interfere with the Routemap character matching. Currently it seems only `*text` is recognized by the editor.

**Comment by xingrz** [comment]
would you please provide a map for test?

**Comment by xingrz** [comment]
Done
