### ISSUE TITLE
missing support for icon links

### ISSUE THREAD

**Issue by xingrz** [xingrz/rdt-editor#5]
https://zh.wikipedia.org/wiki/%E6%A8%A1%E5%9D%97:Routemap#%E5%9C%96%E6%A8%99%E9%87%8D%E7%96%8A%E8%88%87%E5%9C%96%E6%A8%99%E9%8F%88%E6%8E%A5

```
uBHF!@超級站
```

**Comment by Arnie97** [comment]
Should there be an input box to allow custom choice among different language editions of Wikipedia?

**Comment by xingrz** [comment]
> Should there be an input box to allow choice among different language editions of Wikipedia?

Good idea.

**Comment by xingrz** [comment]
Addressed in 0b66ac1. Click-to-open is not implemented yet (maybe in V5), just workaround to correctly render the icon.
