### ISSUE TITLE
Correct stacking order of elements

### ISSUE THREAD

**Issue by jc86035** [xingrz/rdt-editor#7]
The stacking order should be changed to match that of Routemap. In Routemap, if you write e.g. `dSTRq!~lACC\CONTfq`, `lACC` will appear over both other icons. This is because the lowest object in an “overlay stack” (in this case `dSTRq`, `CONTfq`) is layered below any objects to the left which are stacked higher (in this case `lACC`). This is done by only adding `position: absolute` for objects which are not the lowest.

For all objects which are not the lowest, the current behaviour is already correct. However, in rdt-editor, `CONTfq` (in the example) is placed over `lACC`, when it should be below.

**Comment by xingrz** [comment]
Thank you.

**Comment by xingrz** [comment]
Fixed.
